### PR TITLE
Add try/except to catch non standard residues

### LINKED ISSUE #6: Error if structure contains unknown residues.
The error was identified by an user: https://ask.bioexcel.eu/t/whiscy-errors-in-error-log/2881

A closer look at the log show that:
```python
Traceback (most recent call last):
  File "/opt/software/whiscy/bin/whiscy2bfactor.py", line 54, in <module>
    res = STANDARD_TYPES[line[17:20].strip()]
KeyError: 'UNK'
Traceback (most recent call last):
  File "/opt/software/whiscy/bin/whiscy2haddock.py", line 78, in <module>
    res_id = "{}{}".format(STANDARD_TYPES[passive.get_resname()], passive.get_id()[1])
KeyError: 'UNK'
```

### PR DESCRIPTION
**Pull request by rvhonorato**
Since non standard residues are not supported in whiscy, I added a small try/except to catch and ignore them in `whiscy2bfactor.py`, should also resolve #6.

### CODE REVIEW

**Review by amjjbonvin — COMMENTED** [review]
What is now the behaviour? Will it raise an error or filter those out?

**Comment by brianjimenez** [comment]
Will have a look at it and review after holidays 🍻

**Review by brianjimenez — CHANGES_REQUESTED** [review]
Better to print a 0.0 score for UNK or any other non-standard residue:
```
                if line and line.startswith("ATOM  "):
                    try:
                        res = STANDARD_TYPES[line[17:20].strip()]
                        res_num = line[22:26].strip()
                        res_id = "{}{}".format(res, res_num)
                        score = scores[res_id]
                        if args.norm:
                            # Normalized Score = 100 * WHISCYSCORE + 50
                            # Values are truncated between 0 and 100
                            score = max(0.0, min(100.0, 100.0 * (score + 50.0)))
                    except KeyError:
                        score = 0.0

                    line = line[:61] + "%6.2f" % score + line[66:]
                output.write(line + os.linesep)
```

**Comment by rvhonorato** [comment]
@brianjimenez 
> Better to print a 0.0 score for UNK or any other non-standard residue:

Indeed!

@amjjbonvin 
> What is now the behaviour? Will it raise an error or filter those out?

What is happening is that whiscy is producing an error when it tries to add the scores to the bfactor column if the PDB has non-standard residues. With this PR the score of non-standard residues will be 0.0, instead of raising an error.

**Review by brianjimenez — APPROVED** [review]
Looks good!

**Review by amjjbonvin — APPROVED** [review]

**Pull request merged**
